<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>checkBoxCasaUbicacionLaboral</name>
   <tag></tag>
   <elementGuidId>04a8342b-bd71-4fb0-8b9b-4c12190add2f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//epm-radio-button[@id='casa']/div/label/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>epm-radio-checkbox__show epm-radio-checkbox__show--radio</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/app-sede[1]/div[@class=&quot;container epm-encuesta&quot;]/form[@class=&quot;row ng-untouched ng-pristine ng-invalid&quot;]/div[@class=&quot;col-12&quot;]/epm-radio-button[@id=&quot;casa&quot;]/div[@class=&quot;epm-radio-button epm-radio-checkbox&quot;]/label[1]/span[@class=&quot;epm-radio-checkbox__show epm-radio-checkbox__show--radio&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//epm-radio-button[@id='casa']/div/label/span</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/span</value>
   </webElementXpaths>
</WebElementEntity>
