<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>checkBoxEmbarazo</name>
   <tag></tag>
   <elementGuidId>c5657983-7b5d-4fac-ba78-aca6478ed8ea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[13]/epm-checkbox/div/label/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>epm-radio-checkbox__show epm-radio-checkbox__show--checkbox</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/app-encuesta-unica[1]/div[@class=&quot;container epm-encuesta&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12&quot;]/app-grupo-pregunta[1]/div[@class=&quot;epm-grupo-pregunta&quot;]/div[2]/app-pregunta[1]/div[@class=&quot;card epm-pregunta&quot;]/div[@class=&quot;card-body&quot;]/app-respuesta[1]/div[1]/div[1]/epm-checkbox-list[1]/div[@class=&quot;epm-checkbox-list&quot;]/div[@class=&quot;epm-checkbox-list-sintomas ng-untouched ng-pristine ng-valid&quot;]/epm-checkbox[@class=&quot;ng-untouched ng-pristine ng-valid&quot;]/div[@class=&quot;epm-checkbox epm-radio-checkbox epm-checkbox-right&quot;]/label[@class=&quot;epm-checkbox-label&quot;]/span[@class=&quot;epm-radio-checkbox__show epm-radio-checkbox__show--checkbox&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[13]/epm-checkbox/div/label/span[2]</value>
   </webElementXpaths>
</WebElementEntity>
