<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>checkBoxConvivePersonasFactoresDeRiesgoSi</name>
   <tag></tag>
   <elementGuidId>4821d5f0-610b-4a16-b2db-ec7e8ffa1d2d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//epm-radio-button/div/label/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>epm-radio-checkbox__show epm-radio-checkbox__show--radio</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/app-encuesta-unica[1]/div[@class=&quot;container epm-encuesta&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12&quot;]/app-grupo-pregunta[1]/div[@class=&quot;epm-grupo-pregunta&quot;]/div[3]/app-pregunta[1]/div[@class=&quot;card epm-pregunta&quot;]/div[@class=&quot;card-body&quot;]/app-respuesta[1]/div[1]/div[1]/epm-radio-button-multiple[@class=&quot;ng-untouched ng-pristine ng-valid&quot;]/div[1]/epm-radio-button[@class=&quot;ng-valid ng-touched ng-dirty&quot;]/div[@class=&quot;epm-radio-button epm-radio-checkbox&quot;]/label[1]/span[@class=&quot;epm-radio-checkbox__show epm-radio-checkbox__show--radio&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//epm-radio-button/div/label/span</value>
   </webElementXpaths>
</WebElementEntity>
