<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Casa - Copy</name>
   <tag></tag>
   <elementGuidId>97d35c23-317d-4f91-90ef-7b38ff754c06</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/app-root/app-sede/div/form/div[1]/epm-radio-button[1]/div/label/span[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>epm-radio-checkbox__show epm-radio-checkbox__show--radio</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/app-sede[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;container epm-encuesta&quot;]/form[@class=&quot;row ng-invalid ng-touched ng-dirty&quot;]/div[@class=&quot;col-12&quot;]/epm-radio-button[@id=&quot;sede&quot;]/div[@class=&quot;epm-radio-button epm-radio-checkbox&quot;]/label[1]/span[@class=&quot;epm-radio-checkbox__show epm-radio-checkbox__show--radio&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//epm-radio-button[@id='sede']/div/label/span</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//epm-radio-button[2]/div/label/span</value>
   </webElementXpaths>
</WebElementEntity>
