<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>checkBoxDoyConsentimientoInformado</name>
   <tag></tag>
   <elementGuidId>6dd33ea3-8581-4b5f-9d7b-1cdec34ac7f8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//epm-checkbox[@id='doyConsentimiento']/div/label/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>epm-radio-checkbox__show epm-radio-checkbox__show--checkbox</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/app-consentimiento[1]/div[@class=&quot;container aviso&quot;]/div[@class=&quot;card&quot;]/div[@class=&quot;card-footer&quot;]/epm-checkbox[@id=&quot;doyConsentimiento&quot;]/div[@class=&quot;epm-checkbox epm-radio-checkbox epm-checkbox-left&quot;]/label[@class=&quot;epm-checkbox-label&quot;]/span[@class=&quot;epm-radio-checkbox__show epm-radio-checkbox__show--checkbox&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//epm-checkbox[@id='doyConsentimiento']/div/label/span</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span</value>
   </webElementXpaths>
</WebElementEntity>
